FROM node:16-alpine

WORKDIR /home/ilovedocker/app

# Затем скопируйте файлы package.json и package-lock.json 
# из поддиректории packages в корень рабочей директории и установите зависимости при помощи npm.
COPY packages/package*.json ./
RUN npm i --omit-dev

# После этого скопируйте исходники проекта из поддиректории src в корень рабочей директории.
COPY ./src ./

# Укажите в Dockerfile в качестве используемого (”экспозируемого”) порта  — 3032.
EXPOSE 3032

# Ну и наконец, измените команду запуска так, 
# чтобы в контейнере запускался файл main.js (в этом вам поможет команда node).

CMD ["node", "main.js"]